[book]
authors = ["Martin Pool"]
language = "en"
src = "src"
title = "cargo-mutants"

[output.html]
git-repository-url = "https://github.com/sourcefrog/cargo-mutants"
edit-url-template = "https://github.com/sourcefrog/cargo-mutants/edit/main/book/{path}"

[output.linkcheck]
follow-web-links = true

[output.linkcheck.http-headers]
'crates\.io' = ["Accept: text/html"]
